name: Run Journey Tests on GitHub
description: Run epr-frontend journey tests

inputs:
  epr-frontend:
    description: commit hash of epr-frontend
  branch:
    description: branch in this repo
    default: main
  journey-test-pr:
    description: is this action being called from a pr in this repo?
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository if not called by Journey Test PR
      if: inputs.journey-test-pr == 'false'
      uses: actions/checkout@v5
      with:
        repository: DEFRA/epr-frontend-journey-tests
        ref: ${{inputs.branch}}

    - uses: actions/setup-node@v5
      with:
        node-version: 22
        cache: npm

    - name: Install
      run: npm i
      shell: bash

    - name: Start docker compose
      shell: bash
      run: |
        EPR_FRONTEND=${{ inputs.epr-frontend }} \
        docker compose up --wait-timeout 300 -d --quiet-pull

    - name: Wait for services to be ready
      shell: bash
      run: |
        echo "Waiting for frontend to be ready..."
        timeout 180 bash -c 'until curl -f http://localhost:3000/health; do sleep 5; done'

    - name: Run the tests
      shell: bash
      run: |
        npm run test:github
        npm run report

    - name: debug
      if: always()
      run: |
        docker compose logs > logs.txt
        docker ps
      shell: bash

    - name: Upload allure report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: ./allure-report

    - name: Upload docker compose logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: docker-compose-logs
        path: ./logs.txt

    - name: Fail this step if FAILED file exists
      if: always()
      run: |
        if [ -f "FAILED" ]; then
          exit 1
        fi
      shell: bash
