name: Run Journey Tests on GitHub
description: Run epr-frontend journey tests

inputs:
  epr-frontend:
    description: commit hash of epr-frontend
  branch:
    description: branch in this repo
    default: main
  journey-test-pr:
    description: is this action being called from a pr in this repo?
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository if not called by Journey Test PR
      if: inputs.journey-test-pr == 'false'
      uses: actions/checkout@v6
      with:
        repository: DEFRA/epr-frontend-journey-tests
        ref: ${{inputs.branch}}

    - name: Check for matching service branch
      if: inputs.journey-test-pr != 'false'
      id: service-branch
      shell: bash
      run: |
        BRANCH="${{ github.head_ref }}"
        if git ls-remote --heads https://github.com/DEFRA/epr-frontend.git "$BRANCH" | grep -q .; then
          echo "ref=$BRANCH" >> "$GITHUB_OUTPUT"
        else
          echo "ref=main" >> "$GITHUB_OUTPUT"
        fi

    - uses: actions/setup-node@v5
      with:
        node-version-file: .nvmrc
        cache: npm

    - name: Install
      run: npm ci
      shell: bash

    - name: Add hosts entry
      run: |
        sudo echo "127.0.0.1 defra-id-stub" | sudo tee -a /etc/hosts
        # Verify it worked
        cat /etc/hosts
      shell: bash

    - name: Start docker compose with matching Service Branch if it is Journey Test PR
      if: inputs.journey-test-pr != 'false'
      shell: bash
      run: |
        EPR_FRONTEND=${{ steps.service-branch.outputs.ref }} \
        docker compose up --wait-timeout 300 -d --quiet-pull

    - name: Start docker compose
      if: inputs.journey-test-pr == 'false'
      shell: bash
      run: |
        EPR_FRONTEND=${{ inputs.epr-frontend }} \
        docker compose up --wait-timeout 300 -d --quiet-pull

    - name: Wait for services to be ready
      shell: bash
      run: |
        echo "Waiting for frontend to be ready..."
        timeout 180 bash -c 'until curl -f http://localhost:3000/health; do sleep 5; done'

    - name: Run the tests
      shell: bash
      run: |
        npm run test:github
        npm run report

    - name: debug
      if: always()
      run: |
        docker compose logs > logs.txt
        docker ps
      shell: bash

    - name: Upload allure report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: ./allure-report

    - name: Upload docker compose logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: docker-compose-logs
        path: ./logs.txt

    - name: Fail this step if FAILED file exists
      if: always()
      run: |
        if [ -f "FAILED" ]; then
          exit 1
        fi
      shell: bash
